### ISSUE TITLE
Infinitly extracting

### ISSUE THREAD

**Issue by DaftPeanut43** [WeebNetsu/masami#2]
I'm following the tutorial and I went to add the mods,but the bar has said "extracting apk" for 2 hours, what do I do?

**Comment by WeebNetsu** [comment]
Hello! Could you please provide me with details of your device? Android version, brand, free storage space, etc? This might be a bug, so I'd like to explore it further. Also, during this time, have you left the app at all or did you stay in the app the whole time?
